version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: ${PROJECT_NAME:-shangri-la}/shangri-la-backend:latest
    container_name: shangri-la-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - BACKEND_PORT=8000
      - VLLM_API_KEY=${VLLM_API_KEY}
    volumes:
      - /mnt/tank/saos_data:/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: ${PROJECT_NAME:-shangri-la}/shangri-la-frontend:latest
    container_name: shangri-la-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      - FRONTEND_PORT=5173
      - VLLM_SERVER_URL=http://${TRUENAS_HOST_IP}:${VLLM_PORT}
    volumes:
      - /mnt/tank/saos_data:/data