"""Baseline

Revision ID: 1912ba819af1
Revises:
Create Date: 2026-07-24 06:42:42.280433

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1912ba819af1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('core_power', sa.Float(), nullable=False),
    sa.Column('modules', sa.JSON(), nullable=True),
    sa.Column('disposition', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automata_name'), 'automata', ['name'], unique=False)
    op.create_table('combat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('turn_order', sa.JSON(), nullable=True),
    sa.Column('current_turn_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_session_location_id'), 'combat_session', ['location_id'], unique=True)
    op.create_table('faction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sa.Enum('consumables', 'equipment', 'crafting_materials', 'steam_tech_components', name='itemcategory'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('faction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrativeresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_updates', sa.JSON(), nullable=True),
    sa.Column('npcs', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playeraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_exploration', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rawresponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('state_updates', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_market_resource_name'), 'resource_market', ['resource_name'], unique=True)
    op.create_table('systemsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_open', sa.Boolean(), nullable=False),
    sa.Column('global_system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=True)
    op.create_table('world_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('affected_locations', sa.JSON(), nullable=True),
    sa.Column('faction_impacts', sa.JSON(), nullable=True),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_events_location_id'), 'world_events', ['location_id'], unique=False)
    op.create_table('world_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_npcs_ids', sa.JSON(), nullable=True),
    sa.Column('active_automata_ids', sa.JSON(), nullable=True),
    sa.Column('global_event', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('world_memories', sa.JSON(), nullable=True),
    sa.Column('is_combat_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bugreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('optimized_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('background', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('steam', sa.Integer(), nullable=False),
    sa.Column('max_steam', sa.Integer(), nullable=False),
    sa.Column('status_effects', sa.JSON(), nullable=True),
    sa.Column('brass_coins', sa.Integer(), nullable=False),
    sa.Column('show_tutorials', sa.Boolean(), nullable=False),
    sa.Column('location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_location_id'), 'character', ['location_id'], unique=False)
    op.create_index(op.f('ix_character_user_id'), 'character', ['user_id'], unique=False)
    op.create_table('npc',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('current_dialogue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disposition', sa.Float(), nullable=False),
    sa.Column('memories', sa.JSON(), nullable=True),
    sa.Column('location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('faction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('status_effects', sa.JSON(), nullable=True),
    sa.Column('is_hostile', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_location_id'), 'npc', ['location_id'], unique=False)
    op.create_table('quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reward_item_id', sa.Integer(), nullable=True),
    sa.Column('reward_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reward_item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_item_id', sa.Integer(), nullable=False),
    sa.Column('result_quantity', sa.Integer(), nullable=False),
    sa.Column('required_faction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['result_item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_session',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.create_table('airship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hull_integrity', sa.Float(), nullable=False),
    sa.Column('fuel_level', sa.Float(), nullable=False),
    sa.Column('current_altitude', sa.Integer(), nullable=False),
    sa.Column('modules', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airship_character_id'), 'airship', ['character_id'], unique=False)
    op.create_table('augmentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('body_part', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('augmentation_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stat_bonus', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_augmentation_body_part'), 'augmentation', ['body_part'], unique=False)
    op.create_index(op.f('ix_augmentation_character_id'), 'augmentation', ['character_id'], unique=False)
    op.create_table('factionstanding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('standing', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factionstanding_character_id'), 'factionstanding', ['character_id'], unique=False)
    op.create_index(op.f('ix_factionstanding_faction_id'), 'factionstanding', ['faction_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('narration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_updates', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entry_character_id'), 'ledger_entry', ['character_id'], unique=False)
    op.create_table('minigame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minigame_character_id'), 'minigame', ['character_id'], unique=False)
    op.create_index(op.f('ix_minigame_type'), 'minigame', ['type'], unique=False)
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('income_per_tick', sa.Integer(), nullable=False),
    sa.Column('property_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_location_id'), 'property', ['location_id'], unique=False)
    op.create_table('queststate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('available', 'active', 'completed', 'failed', name='queststateenum'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reciperequirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_npc_id'), 'worker', ['npc_id'], unique=False)
    op.create_index(op.f('ix_worker_property_id'), 'worker', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_property_id'), table_name='worker')
    op.drop_index(op.f('ix_worker_npc_id'), table_name='worker')
    op.drop_table('worker')
    op.drop_table('reciperequirement')
    op.drop_table('queststate')
    op.drop_index(op.f('ix_property_location_id'), table_name='property')
    op.drop_table('property')
    op.drop_index(op.f('ix_minigame_type'), table_name='minigame')
    op.drop_index(op.f('ix_minigame_character_id'), table_name='minigame')
    op.drop_table('minigame')
    op.drop_index(op.f('ix_ledger_entry_character_id'), table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_factionstanding_faction_id'), table_name='factionstanding')
    op.drop_index(op.f('ix_factionstanding_character_id'), table_name='factionstanding')
    op.drop_table('factionstanding')
    op.drop_index(op.f('ix_augmentation_character_id'), table_name='augmentation')
    op.drop_index(op.f('ix_augmentation_body_part'), table_name='augmentation')
    op.drop_table('augmentation')
    op.drop_index(op.f('ix_airship_character_id'), table_name='airship')
    op.drop_table('airship')
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_table('recipe')
    op.drop_table('quest')
    op.drop_index(op.f('ix_npc_location_id'), table_name='npc')
    op.drop_table('npc')
    op.drop_index(op.f('ix_character_user_id'), table_name='character')
    op.drop_index(op.f('ix_character_location_id'), table_name='character')
    op.drop_table('character')
    op.drop_table('bugreport')
    op.drop_table('world_state')
    op.drop_index(op.f('ix_world_events_location_id'), table_name='world_events')
    op.drop_table('world_events')
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('systemsettings')
    op.drop_index(op.f('ix_resource_market_resource_name'), table_name='resource_market')
    op.drop_table('resource_market')
    op.drop_table('rawresponse')
    op.drop_table('prompt')
    op.drop_table('playeraction')
    op.drop_table('narrativeresult')
    op.drop_table('location')
    op.drop_table('item')
    op.drop_table('faction')
    op.drop_index(op.f('ix_combat_session_location_id'), table_name='combat_session')
    op.drop_table('combat_session')
    op.drop_index(op.f('ix_automata_name'), table_name='automata')
    op.drop_table('automata')
    # ### end Alembic commands ###
