"""Add condition to location

Revision ID: b206b660a4ae
Revises: 1912ba819af1
Create Date: 2026-07-24 19:46:39.667919

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'b206b660a4ae'
down_revision: Union[str, Sequence[str], None] = '1912ba819af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
